In [1]:
#Q1.


import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

if list_ == array_list.tolist():
    print("No difference in data types between list_ and array_list")
else:
    print("Difference in data types between list_ and array_list")
    print("Data type of list_:", type(list_[0]))
    print("Data type of array_list:", type(array_list[0]))

No difference in data types between list_ and array_list


In [2]:
#Q2.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("Data types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
#Q3.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("Data types of elements in array_list:")
for item in array_list:
    print(type(item))
    
    
#In this case, after changing the data type to int, the elements in array_list will have data type numpy.int64, while the elements in list_ will remain as strings.

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
#Q4.

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Finding the shape of num_array
shape = num_array.shape

# (ii) Finding the size of num_array
size = num_array.size

print("Shape:", shape)
print("Size:", size)

Shape: (2, 3)
Size: 6


In [5]:
#Q5.

import numpy as np

# Create a numpy array of zeros with shape (3, 3)
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#Q6.


import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
